### ISSUE TITLE
suggestion: replace TextEncoder / TextDecoder with a simple UTF8 encoder/decoder implements for code-size

### ISSUE THREAD

**Issue by WanderWang** [soyemi/ts-binary-serializer#2]
![image](https://user-images.githubusercontent.com/2238280/49692899-00b4fb00-fba0-11e8-9bc8-0cb17516d875.png)

**Comment by soyemi** [comment]
Yep, you are right. We should use a more elegant way for text encoding.  I'll add it later.

**Comment by soyemi** [comment]
Hi @WanderWang , I just submit a [commit](https://github.com/soyemi/ts-binary-serializer/commit/2ba167a25aacefe76373ca4de36f7e6ae8633579) for fixing this isssue. 
If there are any further problems, please reopen this issue.
